### ISSUE TITLE
Where to place `decisions` in roadmap

### ISSUE THREAD

**Issue by lwjohnst86** [seedcase-project/community#68]
> I would've expected `decisions` to be under "Explanations"?

_Originally posted by @signekb in https://github.com/seedcase-project/community/pull/67#discussion_r1856525035_
          
Add more discussion points about this here.

**Comment by signekb** [comment]
This is such an interesting discussion, bc - to me - it feel obvious that `decisions` should be under Explanations. Especially after reading the entirety of diataxis' Explanation and Reference page 😁 😅 

In the (quite long - sorry) sections below, I have picked out the quotes that (I believe) argue for `decisions` to be under Explanation.

## Quotes from diataxis' [Explanation](https://diataxis.fr/explanation/) page (emphasis in **bold** by me): 
> It does not take the user’s eye-level view, as in a how-to guide, or a close-up view of the machinery, like reference material.

Here, I think that I would argue that choice of dependencies are beyond a "close-up view of the machinery" - but i'll look into that when I read the Reference page. 

> Explanation is characterised by its distance from the active concerns of the practitioner. It **doesn’t have direct implications** for what they do, or for their work. 

The decisions themselves, naturally, have implications for what the users do and their work - like e.g., relying on the Data Package specification impacts how we structure metadata (in the `datapackage.json`). But, the *explanation*/background of *why* we *chose* this specification does not have *direct* implications on their work. 

> The word explanation - and its cognates in other languages - refer to **unfolding**, the revelation of what is hidden in the folds. So explanation **brings to the light things that were implicit** 

Again, I - at least - think of the decisions as unfolding the *why* of why we do what we do, why we rely on x, y, z, etc. 

> In the case of explanation, it’s useful to have a real or imagined *why* question to serve as a prompt.

..Which is exactly what we do in the `decisions`.

> Your explanation documentation doesn’t need to be called Explanation. Alternatives include: Discussion, **Background**. Conceptual guides, Topics

To me, the `decisions` could also be called Background. 

> Provide background and context in your explanation: **explain *why* things are so** - design decisions, historical reasons, technical constraints - draw implications, mention specific examples.

> Admit opinion and perspective. Explanation can and must **consider alternatives**, counter-examples or **multiple different approaches** to the same question.

We include alternatives or different approaches in the decision posts and offer our *opinions* about them as well.

> In explanation, **you’re not giving instruction or describing facts** - you’re opening up the topic for consideration. It helps to think of explanation as discussion: discussions can even consider and weigh up contrary opinions.

Where it becomes "muddy". You could see a decision post as describing a "fact" of *why* are we doing it this way, but you could also see it as a discussion and consideration of alternatives that ends up with a conclusion of what fits us the best - *in our opinion*

> Things to discuss
	- the bigger picture
	- history
	- **choices, alternatives, possibilities**
	- **why: reasons and justifications**

This fits almost perfectly with `decisions`: They are discussions on the possibilities and alternatives and then end with a choice. It's exactly the reasoning and justifications of the "why", which is also explicit in what we have named them "Why GitHub flow", "Why Frictionsless", etc.

> The language of explanation. *W is better than z, because …*, *The reason for x is because historically, y …*

Also fits with the language we use in the decision posts. In the conclusions we usually write, "We chose option X, because ..."

## Quotes from diataxis' [Reference](https://diataxis.fr/reference/) page (emphasis in **bold** by me): 

> Reference guides are technical descriptions of the machinery and **how to operate it**. 

I don't believe the decisions describe how the user should operate our "machinery" itself, e.g., `sprout`, but rather the *whys* of the way we work, the dependencies we rely on, etc.

> In the case of software, reference guides **describe the software itself** - APIs, classes, functions and so on - and how to use them.

Which is *not* what we do in the decision posts.  We don't describe functions and classes - and we don't describe how to use these functions, classes, etc. 

>  it can and often needs to include a description of how something works or the correct way to use it.

Also not something we cover in the decision posts. 

> Neutral description is the key imperative of technical reference.

The decision posts are opinionated; we describe the pros and cons in relation to *our requirements* and we *weigh* them in terms of what we *believe* will work best *for us*

> Provide examples. [...] For example, an **example of usage of a command** can be a succinct way of illustrating it and its context, without falling into the trap of trying to explain or instruct.

Examples like this, illustrating the "machinery" and *how* it works, are not what we do in the decision posts.

> The language of reference guides. *Django’s default logging configuration inherits Python’s defaults. It’s available as django.utils.log.DEFAULT_LOGGING and defined in django/utils/log.py* [...], *Sub-commands are: a, b, c, d, e, f.*,

The examples provided in the reference guides do not reflect the language we use in our decision posts. In those posts, we do not merely describe commands, configurations, etc.; rather, we *explain* the *background* and *reasons* behind 
*why* we do what we do and how we work.

Thoughts? 😄

**Comment by lwjohnst86** [comment]
Great comments!! :tada: :star_struck: Very eloquently written :grin: 

I think I also agree with you, except for one major thing that I'd like you to respond to and give ideas on... We talked about, given the nature of reference docs, they don't have a clear "product" output and associated DOI. It's difficult to call some reference doc "done". But explanation docs *do* have a natural "product", associated DOI, and we can theoretically and practically call an "explanation" done after we've finished explaining the thing. How do you envision the decision docs to be "done"? What does that look like? Do we generate a "book" type product that we upload to get a DOI whenever a new decision post is added?

If we decide to go the explanation route, I think we should reorganize/revise/edit the docs to fit more of an explanation format/structure rather than an often very objective, fact based description of things.

**Comment by signekb** [comment]
Thanks 👍 

### When to call explanation docs like `design` done

To be able to call e.g., the `decisions` repository "done", I think we need a clear(er) definition of what decisions need such a post. At least, that is not entirely clear to me yet. For instance, we seem to write decision posts for *most, but not all* dependencies we introduce in `sprout` (like `pytest`, `poetry`, but not e.g., `polars`). We also include decision posts on what tools we use for e.g., project management (why GitHub project board, why FigJam), how we work together (why Discord, why GitHub flow. why), 

If we have a clearer definition of what needs to be included in that documentation, it will be easier to judge whether it's "done". 

### About "classifying" entire repos as one type of documentation

Looking at the "remaining" repos under Reference in the roadmap now (if we agree that `decisions` should be moved to Explanation docs), I start wondering if the repos in their entirety are actually *solely* Reference docs. To me, the clearest example of Reference documentation that we have currently is the [reference docs for `sprout`](https://sprout.seedcase-project.org/docs/reference/), but that falls under the `sprout` repo, which is software in the Roadmap). 

Another example would be `team` that includes both "Onboarding" and "How we work" which I would think of as "How-to docs" and the "Events" which could be thought of as Reference, maybe?

**Comment by signekb** [comment]
^The discussions above are also moving away from the original intent of this issue. So, maybe we should create a new issue for this.
